package kafka;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stream_message_list.proto

public final class StreamMessageList {
  private StreamMessageList() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 message_num = 1;
    boolean hasMessageNum();
    int getMessageNum();
    
    // repeated bytes messages = 2;
    java.util.List<com.google.protobuf.ByteString> getMessagesList();
    int getMessagesCount();
    com.google.protobuf.ByteString getMessages(int index);
    
    // required int32 parse_type = 3;
    boolean hasParseType();
    int getParseType();
  }
  public static final class MessageList extends
      com.google.protobuf.GeneratedMessage
      implements MessageListOrBuilder {
    // Use MessageList.newBuilder() to construct.
    private MessageList(Builder builder) {
      super(builder);
    }
    private MessageList(boolean noInit) {}
    
    private static final MessageList defaultInstance;
    public static MessageList getDefaultInstance() {
      return defaultInstance;
    }
    
    public MessageList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StreamMessageList.internal_static_MessageList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StreamMessageList.internal_static_MessageList_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 message_num = 1;
    public static final int MESSAGE_NUM_FIELD_NUMBER = 1;
    private int messageNum_;
    public boolean hasMessageNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getMessageNum() {
      return messageNum_;
    }
    
    // repeated bytes messages = 2;
    public static final int MESSAGES_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> messages_;
    public java.util.List<com.google.protobuf.ByteString>
        getMessagesList() {
      return messages_;
    }
    public int getMessagesCount() {
      return messages_.size();
    }
    public com.google.protobuf.ByteString getMessages(int index) {
      return messages_.get(index);
    }
    
    // required int32 parse_type = 3;
    public static final int PARSE_TYPE_FIELD_NUMBER = 3;
    private int parseType_;
    public boolean hasParseType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getParseType() {
      return parseType_;
    }
    
    private void initFields() {
      messageNum_ = 0;
      messages_ = java.util.Collections.emptyList();;
      parseType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMessageNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasParseType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, messageNum_);
      }
      for (int i = 0; i < messages_.size(); i++) {
        output.writeBytes(2, messages_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, parseType_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, messageNum_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < messages_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(messages_.get(i));
        }
        size += dataSize;
        size += 1 * getMessagesList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, parseType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static StreamMessageList.MessageList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static StreamMessageList.MessageList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static StreamMessageList.MessageList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static StreamMessageList.MessageList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static StreamMessageList.MessageList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static StreamMessageList.MessageList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static StreamMessageList.MessageList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static StreamMessageList.MessageList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static StreamMessageList.MessageList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static StreamMessageList.MessageList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(StreamMessageList.MessageList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements StreamMessageList.MessageListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StreamMessageList.internal_static_MessageList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StreamMessageList.internal_static_MessageList_fieldAccessorTable;
      }
      
      // Construct using StreamMessageList.MessageList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        messageNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        messages_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        parseType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StreamMessageList.MessageList.getDescriptor();
      }
      
      public StreamMessageList.MessageList getDefaultInstanceForType() {
        return StreamMessageList.MessageList.getDefaultInstance();
      }
      
      public StreamMessageList.MessageList build() {
        StreamMessageList.MessageList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private StreamMessageList.MessageList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        StreamMessageList.MessageList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public StreamMessageList.MessageList buildPartial() {
        StreamMessageList.MessageList result = new StreamMessageList.MessageList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageNum_ = messageNum_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          messages_ = java.util.Collections.unmodifiableList(messages_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.messages_ = messages_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.parseType_ = parseType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof StreamMessageList.MessageList) {
          return mergeFrom((StreamMessageList.MessageList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(StreamMessageList.MessageList other) {
        if (other == StreamMessageList.MessageList.getDefaultInstance()) return this;
        if (other.hasMessageNum()) {
          setMessageNum(other.getMessageNum());
        }
        if (!other.messages_.isEmpty()) {
          if (messages_.isEmpty()) {
            messages_ = other.messages_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMessagesIsMutable();
            messages_.addAll(other.messages_);
          }
          onChanged();
        }
        if (other.hasParseType()) {
          setParseType(other.getParseType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMessageNum()) {
          
          return false;
        }
        if (!hasParseType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              messageNum_ = input.readInt32();
              break;
            }
            case 18: {
              ensureMessagesIsMutable();
              messages_.add(input.readBytes());
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              parseType_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 message_num = 1;
      private int messageNum_ ;
      public boolean hasMessageNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getMessageNum() {
        return messageNum_;
      }
      public Builder setMessageNum(int value) {
        bitField0_ |= 0x00000001;
        messageNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessageNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageNum_ = 0;
        onChanged();
        return this;
      }
      
      // repeated bytes messages = 2;
      private java.util.List<com.google.protobuf.ByteString> messages_ = java.util.Collections.emptyList();;
      private void ensureMessagesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          messages_ = new java.util.ArrayList<com.google.protobuf.ByteString>(messages_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<com.google.protobuf.ByteString>
          getMessagesList() {
        return java.util.Collections.unmodifiableList(messages_);
      }
      public int getMessagesCount() {
        return messages_.size();
      }
      public com.google.protobuf.ByteString getMessages(int index) {
        return messages_.get(index);
      }
      public Builder setMessages(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMessagesIsMutable();
        messages_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addMessages(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMessagesIsMutable();
        messages_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllMessages(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureMessagesIsMutable();
        super.addAll(values, messages_);
        onChanged();
        return this;
      }
      public Builder clearMessages() {
        messages_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      
      // required int32 parse_type = 3;
      private int parseType_ ;
      public boolean hasParseType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getParseType() {
        return parseType_;
      }
      public Builder setParseType(int value) {
        bitField0_ |= 0x00000004;
        parseType_ = value;
        onChanged();
        return this;
      }
      public Builder clearParseType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        parseType_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:MessageList)
    }
    
    static {
      defaultInstance = new MessageList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:MessageList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MessageList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031stream_message_list.proto\"H\n\013MessageLi" +
      "st\022\023\n\013message_num\030\001 \002(\005\022\020\n\010messages\030\002 \003(" +
      "\014\022\022\n\nparse_type\030\003 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MessageList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MessageList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MessageList_descriptor,
              new java.lang.String[] { "MessageNum", "Messages", "ParseType", },
              StreamMessageList.MessageList.class,
              StreamMessageList.MessageList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
